### ISSUE TITLE
Port pic24 build system to scons and build unit testing infrastructure

### ISSUE THREAD

**Issue by timburke** [WellDone/MoMo-Firmware#95]
This issue tracks progress on getting off of ceedling (which is terrible) and onto the same SCons based system that builds the 8-bit code.  

**Tasks**
- [x] Build xc16 compilation tools
- [x] Port PIC24 modules and shared library to scons
- [x] Build 16-bit unit testing framework
- [x] Unify unit testing frameworks (8 and 16 bit)
- [ ] Document build system
- [ ] Deprecate duplicate functionality and port over to new ChipSettings, ChipFamily for hosting all chip specific information

**Outstanding Issues**
- [ ] Dependency on pic24 shared library is not explicit.  Changes to shared library will not trigger rebuild of pic24 modules  
- [ ] Unit tests on 8 bit code are difficult to write

**Comment by timburke** [comment]
Basic build system documentation at:
https://github.com/WellDone/MoMo-Firmware/wiki/MoMo-Build-System
